- name: Install Chocolatey/SSH/Git
  hosts: windows
  gather_facts: false
  tasks:
    - name: Install Chocolatey Windows Package Manager
      win_chocolatey:
        name: chocolatey
        state: present
    - name: Install Git
      win_chocolatey:
        name: git
        state: present
    - name: Install openssh
      win_chocolatey:
        name: openssh
        package_params: /SSHServerFeature
        state: present
      tags: openssh
    - name: Copy SSH public key to host
      win_copy:
        src:  /cygdrive/c/Users/nizam/.ssh/id_rsa.pub
        dest: C:\ProgramData\ssh\administrators_authorized_keys 
      tags: openssh

    - name: Disable inheritence
      win_acl_inheritance:
        path: C:\ProgramData\ssh\administrators_authorized_keys
        state: absent
      tags: openssh

    - name: Set the owner on the authorised keys file.
      win_owner:
        path: C:\ProgramData\ssh\administrators_authorized_keys
        user: "{{ ansible_hostname }}\\Administrators"
      tags: openssh

    - name: Don't allow users to view the file
      win_acl:
        path: C:\ProgramData\ssh\administrators_authorized_keys
        user: "Authenticated Users"
        rights: Read,Write,Modify,FullControl,Delete
        type: allow
        state: absent
      tags: openssh

    - name: Do allow admins to access the file
      win_acl:
        path: C:\ProgramData\ssh\administrators_authorized_keys
        user: "{{ item }}"
        rights: FullControl
        type: allow
        state: present
      with_items:
        - SYSTEM
        - "{{ ansible_hostname }}\\Administrators"
      tags: openssh
