- name: Install Chocolatey/SSH/Git
  hosts: windows
  gather_facts: false
  tasks:
    - name: Install Chocolatey Windows Package Manager
      win_chocolatey:
        name: chocolatey
        state: present

    - name: Install Git using Chocolatey
      win_chocolatey:
        name: git
        state: present

    - name: Install openssh
      win_chocolatey:
        name: openssh
        params: /SSHServerFeature /KeyBasedAuthenticationFeature

    - name: Disable common authorized key file for administrators group in sshd_config
      win_lineinfile:
        path: '%ProgramData%\ssh\sshd_config'
        regexp: 'AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys'
        line: '# AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys'

    - name: Configure and enable SSH on standard port 
      win_firewall_rule:
       name: OpenSSH
       localport: 22
       action: allow
       direction: in
       protocol: tcp

    - name: Set up authorised key file
      win_lineinfile:
        path: '%ProgramData%\ssh\administrators_authorized_keys'
        line: "{{ lookup('file', '/cygdrive/c/Users/nizam/.ssh/id_rsa.pub') }}"
        create: Yes

    - name: Disable inheritence
      win_acl_inheritance:
        path: C:\ProgramData\ssh\administrators_authorized_keys
        state: absent

    - name: Set the owner on the authorised keys file.
      win_owner:
        path: C:\ProgramData\ssh\administrators_authorized_keys
        user: "{{ ansible_hostname }}\\Administrators"

    - name: Don't allow users to view the file
      win_acl:
        path: C:\ProgramData\ssh\administrators_authorized_keys
        user: "Authenticated Users"
        rights: Read,Write,Modify,FullControl,Delete
        type: allow
        state: absent

    - name: Do allow admins to access the file
      win_acl:
        path: C:\ProgramData\ssh\administrators_authorized_keys
        user: "{{ item }}"
        rights: FullControl
        type: allow
        state: present
      with_items:
        - SYSTEM
        - "{{ ansible_hostname }}\\Administrators"
