- name: Install Chocolatey/SSH/Git
  hosts: windows
  gather_facts: true
  tasks:
    - name: Install Chocolatey Windows Package Manager
      win_chocolatey:
        name: chocolatey
        state: present

    - name: Upgrade installed packages
      win_chocolatey:
        name: all
        state: latest

    - name: Install Git using Chocolatey
      win_chocolatey:
        name: git
        version: "2.36.0"
        state: present

    - name: Install openssh
      win_chocolatey:
        name: openssh
        package_params: /SSHServerFeature /KeyBasedAuthenticationFeature
        state: present

    - name: Configure default shell to PowerShell
      win_regedit:
        path: HKLM:\SOFTWARE\OpenSSH
        name: DefaultShell
        data: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
        type: string
        state: present

    - name: Enable PubkeyAuthentication yes in sshd_config
      win_lineinfile:
        path: '%ProgramData%\ssh\sshd_config'
        regexp: "#PubkeyAuthentication yes"
        line: "PubkeyAuthentication yes"

    - name: StrictModes no in sshd_config
      win_lineinfile:
        path: '%ProgramData%\ssh\sshd_config'
        regexp: "#StrictModes yes"
        line: "StrictModes no"

    - name: Configure and enable SSH on standard port
      win_firewall_rule:
        name: OpenSSH
        localport: 22
        action: allow
        direction: in
        protocol: tcp

    - name: Generate administrators_authorized_keys file
      win_lineinfile:
        path: '%ProgramData%\ssh\administrators_authorized_keys'
        line: "{{ lookup('file', '/home/nisam/.ssh/casestudy.pub') }}"
        create: Yes

    - name: Remove any other permission entires from administrators_authorized_keys
      win_acl_inheritance:
        path: C:\ProgramData\ssh\administrators_authorized_keys
        state: absent

    - name: Add owner on administrators_authorized_keys.
      win_owner:
        path: C:\ProgramData\ssh\administrators_authorized_keys
        user: "{{ ansible_hostname }}\\Ansible"

    - name: Allow Administrators & SYSTEM to access the file
      win_acl:
        path: C:\ProgramData\ssh\administrators_authorized_keys
        user: "{{ item }}"
        rights: FullControl
        type: allow
        state: present
      with_items:
        - SYSTEM
        - "{{ ansible_hostname }}\\Administrators"
