pipeline{
    agent any

    stages{

        stage('Packer Image Build'){
          steps{
              sh "packer validate windows_10_winrm.json"
              sh "packer build windows_10_winrm.json"
          }
        }

        stage('Terraform Apply'){
          steps{
              sh "terraform init"
              sh "terraform apply -auto-approve"
          }
        }

    }
}
