pipeline{
    agent any

    stages{

       /* stage('Packer Image Build'){
          steps{
            dir("automate_windows_host") {
              bat "packer validate windows_10_winrm.json"
              bat "packer build windows_10_winrm.json"
            }
          }
        }*/

        stage('Terraform Apply'){
          steps{
            dir("automate_windows_host") {
            def tfHome = tool name: 'Terraform', type: 'com.cloudbees.jenkins.plugins.customtools.CustomTool'
            env.Path = "${tfHome};${env.Path}"
              bat "terraform init"
              bat "terraform apply -auto-approve"
            }
          }
        }

    }
}
